avito:
  target_url: "https://www.avito.ru/moskva/telefony/mobilnye_telefony/apple-ASgBAgICAkS0wA3OqzmwwQ2I_Dc?f=ASgBAQICA0S0wA3OqzmwwQ2I_Dfyig6kgpQBAUDo6w4k_P3bAvr92wI&s=104&user=1"
  
  pages_to_scan: 1

model:
  profit_threshold: 5000

airflow:
  schedule_interval: '*/30 * * * *'